# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

cache:
  - C:\RLibrary

environment:
  global:
    NOT_CRAN: true
    USE_RTOOLS: true
    WARNINGS_ARE_ERRORS: 1
    _R_CHECK_FORCE_SUGGESTS_: 0
    PYTHON_VERSION: 3.6
    MINICONDA: C:\Miniconda3-x64
    RETICULATE_PYTHON: C:\Miniconda3-x64\python.exe    
  # env vars that may need to be set, at least temporarily, from time to time
  # see https://github.com/krlmlr/r-appveyor#readme for details
  # USE_RTOOLS: true
  # R_REMOTES_STANDALONE: true

# Adapt as necessary starting from here
install:
  - ps: Bootstrap
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - if exist "requirements.txt" conda update -q conda
  - if exist "requirements.txt" conda info -a
  - if exist "requirements.txt" conda create -c bioconda -q -n r-reticulate python="%PYTHON_VERSION%" --file requirements.txt || true
  - if exist "requirements.txt" activate r-reticulate && pip install -r requirements.txt || true
  - git config core.longpaths true
  - git config --system core.longpaths true

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
